### ISSUE TITLE
Projections are undefined when querying __typename

### ISSUE THREAD

**Issue by mathieutu** [b1f6c1c4/graphql-advanced-projection#12]
With 
```graphql
query LastCampaign {
  lastCampaign {
    id
    title
    questions {
      id
      message
    }
  }
}
```
it works, 

With 
```graphql
query LastCampaign {
  lastCampaign {
    id
    title
    questions {
      id
      message
      __typename
    }
  }
}
```

It doesn't.

We should be able to add __typename with any consequences in queries (and apollo does that: https://stackoverflow.com/questions/45509228/why-do-graphql-fragments-need-typename-in-queries). 

https://graphql.org/learn/queries/#meta-fields

**Comment by mathieutu** [comment]
The logs : 
```log
graphql-advanced-projection error: Projecting TypeError: Cannot read property 'type' of undefined
  graphql-advanced-projection     at context.selectionSet.selections.forEach (/Users/mathieutu/Projects/askip/node_modules/graphql-advanced-projection/src/core.js:23:60)
  graphql-advanced-projection     at Array.forEach (<anonymous>)
  graphql-advanced-projection     at /Users/mathieutu/Projects/askip/node_modules/graphql-advanced-projection/src/core.js:18:37
  graphql-advanced-projection     at fieldFunc (/Users/mathieutu/Projects/askip/node_modules/graphql-advanced-projection/src/projection.js:58:33)
  graphql-advanced-projection     at context.selectionSet.selections.forEach (/Users/mathieutu/Projects/askip/node_modules/graphql-advanced-projection/src/core.js:25:29)
  graphql-advanced-projection     at Array.forEach (<anonymous>)
  graphql-advanced-projection     at /Users/mathieutu/Projects/askip/node_modules/graphql-advanced-projection/src/core.js:18:37
  graphql-advanced-projection     at /Users/mathieutu/Projects/askip/node_modules/graphql-advanced-projection/src/core.js:69:6
  graphql-advanced-projection     at /Users/mathieutu/Projects/askip/node_modules/graphql-advanced-projection/src/projection.js:78:41
  graphql-advanced-projection     at parseInfo (/Users/mathieutu/Projects/askip/server/mongo/projections.ts:23:25)
  graphql-advanced-projection     at lastCampaign (/Users/mathieutu/Projects/askip/server/graphql/resolvers.ts:21:50)
  graphql-advanced-projection     at field.resolve (/Users/mathieutu/Projects/askip/node_modules/graphql-extensions/dist/index.js:92:48)
  graphql-advanced-projection     at resolveFieldValueOrError (/Users/mathieutu/Projects/askip/node_modules/graphql/execution/execute.js:531:18)
  graphql-advanced-projection     at resolveField (/Users/mathieutu/Projects/askip/node_modules/graphql/execution/execute.js:495:16)
  graphql-advanced-projection     at /Users/mathieutu/Projects/askip/node_modules/graphql/execution/execute.js:364:18
  graphql-advanced-projection     at Array.reduce (<anonymous>) +2ms
```
